name: Autorelease on version up

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: true
      matrix:
        node_version:
          - 18.x

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - name: Setup node (manual)
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}\n registry=https://npm.pkg.github.com/\n always-auth=true" > ~/.npmrc
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build & assemble package
        run: yarn package
      - name: Publish package
        working-directory: ./build/package
        run: npm publish
