name: Autorelease on new release

on:
  release:
    types: [ created ]

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: true
      matrix:
        node_version:
          - 18.x

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      #- name: Setup node (manual)
      #  run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}\n registry=https://npm.pkg.github.com/\n always-auth=true" > ~/.npmrc
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build & assemble package
        run: yarn package
      - name: Publish package
        run: yarn publish
        working-directory: ./build/package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
