name: Autorelease on version up

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node_version:
          - 18.x

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build project
        run: yarn build
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
